server:
  port: 9998
  logger:
    level: DEBUG
    home: /tmp/logs


database:
  mysql:
    admin:
      database: db_zhouyun_record_album
      driverClassName: com.mysql.jdbc.Driver
      host: 106.14.239.111
      port: 3306
      username: dev
      password: Bq2W0n3nXOPScwE9SZhozV9LMsP9HxevrAYa1KncgIDmwvERazuyAWxJPO7v4OkGrMak1cUBwQmJjke03y4KQw==
      configDecrypt: true
      configDecryptkey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIaYR4jxofgZRrHD1FKVF7k3h230YXnrEHejV0W1BDoURGB9xmhDEGq5IctgTuE0FFU5lHBjVSWr/dC0G1PPby8CAwEAAQ==
      url: jdbc:mysql://${database.mysql.admin.host}:${database.mysql.admin.port}/${database.mysql.admin.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      connectionProperties: config.decrypt=${database.mysql.admin.configDecrypt};config.decrypt.key=${database.mysql.admin.configDecryptkey}

redis:
    key-prefix: prod
    host: prod-redis-service.default.svc.cluster.local
    port: 6379
    password: Pi#2018@com
    database: 0
    timeout: 5000
    block-when-exhausted: true
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0




